CLI Template for show lacp commands
project-arlo/sonic-mgmt-framework pull request #139
Opened 2019-09-27 19:20 UTC by ArthiSivanantham

2019-10-04 18:41 UTC, jeffyin-dell requested changes

2019-10-04 18:41 UTC, jeff-yin commented on src/CLI/actioner/sonic-cli-lacp-port-channel.py
> +            api_response = {
The indentation got kind of weird here; can you fix it so that indentations are 4 spaces?

2019-10-04 18:41 UTC, jeff-yin commented on src/CLI/actioner/sonic-cli-lacp-port-channel.py
> +        elif func.__name__ == 'get_openconfig_lacp_lacp_interfaces':
Can you add a comment that this is just placeholder output for now, for the show command?

2019-10-04 18:56 UTC, justinejose91 commented on src/CLI/clitree/cli-xml/sonic_types.xml
> +        pattern="1..128"
Can you delete the LAG_ID existing as well? Looks like there is a LAG_ID with pattern 0..9999 already existing.

2019-10-08 17:28 UTC, closed without merging

2019-10-08 17:29 UTC, ArthiSivanantham commented
As per the discussion with Bhavini and Tejaswi, will be showing lacp information as part of the "show PortChannel" CLI.