WIP: Buzznick wred ecn support
project-arlo/sonic-mgmt-framework pull request #156
Opened 2019-10-09 20:12 UTC by spenugondaa

WIP: This pull request is for CLI template to support wred profile management.
WRED profile takes the following parameters: profile-name, red-min-threshold, red-max-threshold, red-drop-rate, green-min-threshold, green-max-threshold, green-drop-rate, yellow-min-threshold, yellow-max-threshold, yellow-drop-rate and ecn.
As there is no oc yang available, decision has been made to use the sonic yang.
Ref: https://jira.force10networks.com/browse/SNC-1093

sonic-wred-profile.yang contains the model for the profiles.
src/CLI/clitree/cli-xml/wred.xml contains the CLI template
src/CLI/actioner/sonic-cli-wred.py contains the actioner script for get/set/delete
src/CLI/renderer/templates/show_wred.j2 contains renderer script.

ex:
sonic# show wred
---------------------------------------------------
Profile                : myprof4
---------------------------------------------------
Profile                : new3
green-max-threshold    : 100
---------------------------------------------------
Profile                : newprof1
yellow-max-threshold   : 10

sonic(config)# wred prof1
sonic(conf-wred-prof1)#
  ecn                               Configure ecn of the profile
  green-drop-rate          Configure green drop rate of the profile
  green-max-threshold   Configure green maximum threshold of the profile
  green-min-threshold   Configure green minimum threshold of the profile
  no                                 Negate a command or set its defaults
  red-drop-rate               Configure red drop rate of the profile
  red-max-threshold       Configure red maximum threshold of the profile
  red-min-threshold       Configure red minimum threshold of the profile
  yellow-drop-rate         Configure yellow drop rate of the profile
  yellow-max-threshold  Configure yellow maximum threshold of the profile
  yellow-min-threshold  Configure yellow minimum threshold of the profile
sonic(conf-wred-prof1)# green-max-threshold 10
sonic(conf-wred-prof1)# exit
sonic# show wred
---------------------------------------------------
Profile                : myprof4
---------------------------------------------------
Profile                : new3
green-max-threshold    : 100
---------------------------------------------------
Profile                : newprof1
yellow-max-threshold   : 10
---------------------------------------------------
Profile                : prof1
green-max-threshold    : 10

2019-10-14 22:58 UTC, jeff-yin commented
@spenugondaa -- do you need to update your SONiC YANG files to match the _new_ SONiC YANG format?

2019-10-14 23:06 UTC, spenugondaa commented
> @spenugondaa -- do you need to update your SONiC YANG files to match the _new_ SONiC YANG format?

@jeff-yin not for new sonic format but we need to modify the yang file a bit based on the internal HLD review comment. @eddyatdell  will work on it and push the updated yang tomorrow.

2019-11-12 13:57 UTC, dutta-partha requested changes

2019-11-12 13:57 UTC, dutta-partha commented on models/yang/sonic/sonic-wred-profile.yang
> +    revision 2019-05-15 {
Update the date.

2019-11-12 13:57 UTC, dutta-partha commented on models/yang/sonic/sonic-wred-profile.yang
> +                    type uint64;
Define constraint like range of values or special value etc. Take care in all places applicable.

2019-11-12 13:58 UTC, dutta-partha commented on models/yang/sonic/sonic-wred-profile.yang
> +                    type string;
Any specific pattern of the name ?

2019-11-13 05:52 UTC, bhavini-gada commented
Closing as this feature is not planned for Buzznik anymore.

2019-11-13 05:52 UTC, closed without merging