Removing Total power from show platform env output
project-arlo/sonic-mgmt-framework pull request #590
Opened 2020-02-12 00:45 UTC by arunsundark

The total power field is not consistent across all platforms and so we decided to remove it from the output.

2020-02-13 19:00 UTC, DhanaDell approved these changes

2020-02-14 02:04 UTC, joyas-joseph requested changes

2020-02-14 20:18 UTC, joyas-joseph commented on src/translib/pfm_app.go
> +	if strings.Contains(scanner.Text(), "Total Power") {
Do you have a mix of tabs and spaces?

2020-02-14 21:30 UTC, arunsundark commented on src/translib/pfm_app.go
> +	if strings.Contains(scanner.Text(), "Total Power") {
Looks it fixed. Fixed now.

2020-02-15 00:29 UTC, joyas-joseph approved these changes

2020-02-17 04:21 UTC, joyas-joseph approved these changes

2020-02-17 16:36 UTC, merged